### ISSUE TITLE
Could you release the bazzani.h5 in the rmdn_comparison?

### ISSUE THREAD

**Issue by DanqingZ** [ndrplz/dreyeve#2]
Hi I am trying to use your model as well as your implementation of the rmdn for my dataset. I saw in [predict_dreyeve_sequence.py file](https://github.com/ndrplz/dreyeve/blob/master/experiments/rmdn_comparison/predict_dreyeve_sequence.py), a h5 file called bazzani.h5 is loaded. Could you release this weight file so that I can test the model on my dataset as well? Thanks a lot!

**Comment by ndrplz** [comment]
Not sure why this was never answered. Sorry about that. For posterity, as we answered to whom contacted us via email, here we go. Weights from the ICLR 2017 work from _Bazzani et al_ come from our re-implementation of the proposed method ("official" pre-trained models were not released by the authors). Thus, we decided not to share those because we might have introduced bugs / biases during re-implementation and we don't want this to be used as baseline.
